
import Footer from "./components/Footer/Footer";
import Navabr from "./components/Navbar/Navbar";
import "./globals.css";

import { Prompt } from 'next/font/google';

const prompt = Prompt({
  subsets: ['latin'],
  weight: ['400', "600", '700', "800"],
});

export const metadata = {
  title: "Global Enterprise",
  description: "Generated by Inovexa Com ltd",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={prompt.className} >
        <div className=" relative max-w-7xl mx-auto bg-primary">
          <div className="fixed top-0 z-10 w-full">
            <Navabr />
          </div>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
