import DashNavbar from "./_components/DashNavbar/DashNavbar";

export const metadata = {
    title: "DashBoard",
    description: "Generated by Inovexa Com ltd",
};

export default function DashboardLayout({ children }) {
    return (
        <div className=" min-w-7xl grid grid-cols-12 bg-[#000000] text-[#FFD369] min-h-screen py-10 px-2">
            <div className="col-span-2 pt-4">
                <DashNavbar />
            </div>
            <div className="col-span-10 min-h-screen">
                <main>{children}</main>
            </div>
        </div>
    );
}
