
export const metadata = {
    title: "DashBoard",
    description: "Generated by Inovexa Com ltd",
};

export default function DashboardLayout({ children }) {
    return (
        <div className="dashboard-layout py-10">
            <aside>Dashboard Sidebar</aside>
            <main>{children}</main>
        </div>
    );
}
